### ISSUE TITLE
Add a world settings editor (Part 1)

### ISSUE THREAD

**Issue by allejo** [allejo/WebBZEdit#29]
In our menu bar, add a new dropdown menu titled "Map" and this is where editors for map settings will live. This is going to be a larger task that is split up into multiple pieces.

- [x] Change world settings such as wall height, size, free ctf spawn (#30)
- [x] Change map settings like jumping, ricochets, max shots, max players (#43)
- [ ] ~~Allow specifying which flags will exist and how many of them~~ (#46)
- [ ] ~~Setting BZDB variables~~ (#45)

## Todo

- [x] Create a modal that will pop up with different tabs for each of the above editors
- [x] Create separate issues for the tasks above after the modal foundation has been added

**Comment by allejo** [comment]
Closing this as separate issues have now been created for the remaining tasks.
